version: '3'

services:
  fluentd:
    build: ./td-agent
    image: td-agent
    container_name: td-agent
    volumes:
      - "./td-agent/log:/fluentd/log"
      - "./td-agent/td-agent.conf:/fluentd/etc/td-agent.conf"
      - "./nginx/log:/var/log/nginx"
    environment:
      FLUENTD_OPT: "-vv"
      FLUENTD_CONF: "td-agent.conf"
      TZ: "Asia/Tokyo"

  nginx:
    build: ./nginx
    image: nginx
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - "./nginx/log:/var/log/nginx"
      - "./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf"
    environment:
      TZ: "Asia/Tokyo"
