version: '3'

services:
  td-agent2:
    build: ./td-agent2
    image: td-agent2
    container_name: td-agent2
    ports:
      - "24224:24224"
      - "24220:24220"
    volumes:
      - "./td-agent2/td-agent.conf:/etc/td-agent/td-agent.conf"
      - "./td-agent2/transfer.conf:/etc/td-agent/conf.d/transfer.conf"
    environment:
      TZ: "Asia/Tokyo"

  td-agent3:
    build: ./td-agent3
    image: td-agent3
    container_name: td-agent3
    ports:
      - "24424:24424"
      - "24420:24420"
    volumes:
      - "./td-agent3/td-agent.conf:/etc/td-agent/td-agent.conf"
      - "./td-agent3/transfer.conf:/etc/td-agent/conf.d/transfer.conf"
    environment:
      TZ: "Asia/Tokyo"

  nginx:
    build: ./nginx
    image: nginx
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - "./nginx/log:/var/log/nginx"
      - "./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf"
    environment:
      TZ: "Asia/Tokyo"
